service:
  name: aws-nodejs-ecma-script

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  renderPage:
    handler: src/lambda/handler.renderPage
    events:
      - http:
          method: GET
          path: /

custom:
  webpack: "./webpack.config.js"
