service:
  name: lambda-react-demo-fronttalks

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-finch

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs6.10

functions:
  renderPage:
    handler: src/lambda/handler.renderPage
    environment:
      NODE_ENV: "AWS"
    events:
      - http:
          method: GET
          path: /

custom:
  webpack: "./webpack.config.js"
  client:
    bucketName: lambda-react-demo-fronttalks
